### ISSUE TITLE
Failed to activate the linter-golinter package

### ISSUE THREAD

**Issue by tirithen** [AtomLinter/linter-golinter#106]
[Enter steps to reproduce:]

1. With a clean Atom install (removed the .atom directory) install linter-golinter
2. Error message is displayed directly after installation

**Atom**: 1.18.0 x64
**Electron**: 1.4.16
**OS**: "Arch Linux"
**Thrown From**: [linter-golinter](https://github.com/AtomLinter/linter-golinter) package 1.2.2

### Stack Trace

Failed to activate the linter-golinter package

```
At Cannot find module 'sb-config-file'

Error: Cannot find module 'sb-config-file'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:350:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter/lib/linter-registry.js:17:21)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Linter.registryLintersInit (/packages/linter/lib/main.js:117:7)
    at Linter.addLinter (/packages/linter/lib/main.js:170:24)
    at Object.consumeLinterLegacy (/packages/linter/lib/index.js:98:13)
    at Provider.module.exports.Provider.provide (/usr/lib/atom/node_modules/service-hub/lib/provider.js:34:52)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/lib/atom/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/usr/lib/atom/src/package.js:444:71)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:254:16)
    at /usr/lib/atom/src/package.js:223:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:97:15)
    at /usr/lib/atom/src/package.js:216:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:213:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:635:34)
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:505:29
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:322:11)
    at /usr/lib/atom/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
  2x -4:21.5.0 core:confirm (input.hidden-input)
  3x -4:02.8.0 core:move-left (input.hidden-input)
 28x -4:01.3.0 core:move-right (input.hidden-input)
  2x -3:49.2.0 core:move-left (input.hidden-input)
  2x -3:46.6.0 core:confirm (input.hidden-input)
     -3:02.4.0 core:backspace (input.hidden-input)
  4x -3:01.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
go-debug 1.4.3 
go-plus 5.5.5 
go-rename 0.3.0 
go-signature-statusbar 1.2.0 
intentions 1.1.2 
linter 2.2.0 
linter-golinter 1.2.2 
linter-gotype 0.1.0 
linter-govet 0.1.5 
linter-ui-default 1.6.1 
minimap-linter 2.0.0 
```

**Comment by Arcanemagus** [comment]
Please try re-installing the package. APM sometimes fails to install all required dependencies rarely (1/~20,000 odds at a rough estimate).

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
