### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by edoardo849** [AtomLinter/linter-golinter#20]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0-beta3
**System**: Ubuntu 15.10
**Thrown From**: [linter-golinter](https://github.com/AtomLinter/linter-golinter) package, v1.1.0

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At /usr/share/atom-beta/resources/app.asar/src/buffered-process.js:260

Error: spawn ENOTDIR
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom-beta/resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/usr/share/atom-beta/resources/app.asar/src/buffered-process.js:52:14)
    at /home/edoardo849/.atom/packages/linter-golinter/init.coffee:12:9
    at lint (/home/edoardo849/.atom/packages/linter-golinter/init.coffee:8:7)
    at Object.provider.lint (/home/edoardo849/.atom/packages/linter-golinter/init.coffee:60:25)
    at promises.push.Promise.then._this.emitter.emit.linter (/home/edoardo849/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /home/edoardo849/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/home/edoardo849/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /home/edoardo849/.atom/packages/linter/lib/linter.coffee:98:16
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /home/edoardo849/.atom/packages/linter/lib/editor-linter.js:30:20
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom-beta/resources/app.asar/src/workspace.js:643:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom-beta/resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:03.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      ".bin"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.21
atom-jade, v0.3.0
atom-ternjs, v0.12.2
atom-typescript, v8.1.0
color-picker, v2.0.14
docblockr, v0.7.3
environment, v1.1.1
file-icons, v1.6.14
go-config, v0.3.3
go-find-references, v1.2.3
go-plus, v3.5.2
jshint, v1.8.3
linter, v1.11.3
linter-coffeescript, v1.0.0
linter-flake8, v1.9.3
linter-golinter, v1.1.0
meteor-api, v2.20.0
project-manager, v2.7.4
remote-sync, v3.5.0
sync-settings, v0.6.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Did you modify your settings for the executable path at all?

**Comment by edoardo849** [comment]
Solved the issue: being on a brand-new machine I've forgot to add the GOLANG in ~/.bash_profile . Thanks for your fast intervention!
