### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by MarsuperMammal** [AtomLinter/linter-golinter#5]
[Enter steps to reproduce below:]

1. Not sure
2. Opened a new file and typed package main

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-golinter](https://github.com/AtomLinter/linter-golinter) package, v1.0.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at /Users/pwatts/.atom/packages/linter-golinter/init.coffee:12:9
  at lint (/Users/pwatts/.atom/packages/linter-golinter/init.coffee:8:7)
  at Object.provider.lint (/Users/pwatts/.atom/packages/linter-golinter/init.coffee:60:25)
  at Promise.then._this.emitter.emit.linter (/Users/pwatts/.atom/packages/linter/lib/linter-registry.coffee:57:22)
  at LinterRegistry.triggerLinter (/Users/pwatts/.atom/packages/linter/lib/linter-registry.coffee:56:16)
  at /Users/pwatts/.atom/packages/linter/lib/linter-registry.coffee:50:17
  at Array.map (native)
  at /Users/pwatts/.atom/packages/linter/lib/linter-registry.coffee:48:27
  at process._tickCallback (node.js:367:9)

```

### Commands

```
     -3:22 core:close (div.settings-view.pane-item)
  2x -2:41.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -2:41.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -2:06.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  5x -1:47.3.0 core:move-left (atom-text-editor.editor.mini.is-focused)
  7x -1:46.1.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -1:37 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:02.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/pwatts/git"
  },
  "linter-golinter": {
    "executablePath": "/Users/pwatts/go/src/github.com/golang/lint/golint"
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
language-puppet, v0.14.0
language-terraform, v0.5.0
linter, v1.3.4
linter-golinter, v1.0.0
linter-puppet-lint, v0.2.9
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
I think the `executablePath` is invalid, You can not execute a directory, you must give it a path to an executable file.

**Comment by kavu** [comment]
@MarsuperMammal I agree with @steelbrain — your path is likely to be invalid. You use `/Users/pwatts/go/src/github.com/golang/lint/golint` and it's a `src/` dir, not `bin` in `$GOPATH`. For example my path is `/Users/kavu/GOPATH/bin/golint` while my `src` path for golint is `/Users/kavu/GOPATH/src/github.com/golang/lint/golint`, it's similar to yours.

**Comment by VorT3x** [comment]
I have same exception, but my golint executable path is: `/Users/dlogvinenko/Documents/SoftwareDevelopment/golang/bin/`

So it looks correct.

**Comment by steelbrain** [comment]
@VorT3x I am afriad the path is incorrect, it should be a file not a folder.

**Comment by VorT3x** [comment]
@steelbrain lol, that helped! Thanks :)
